

import React, { createContext, useState, useContext, useEffect, useMemo } from 'react';

type Locale = 'en' | 'ar';
type Direction = 'ltr' | 'rtl';
type Translations = Record<string, string>;

interface LocalizationContextType {
  locale: Locale;
  direction: Direction;
  t: (key: string, options?: Record<string, string | number>) => string;
  setLocale: (locale: Locale) => void;
}

const translations: Record<Locale, Translations> = {
  en: {
    cyberSentinel: 'Cyber Sentinel',
    // Main Menu
    casebook: 'Casebook',
    newInvestigation: 'New Investigation',
    vtScanner: 'VirusTotal Scanner',
    uaAnalyzer: 'User-Agent Analyzer',
    vulnScanner: 'Vulnerability Scanner',
    threatIntel: 'Threat Intel Feed',
    soon: 'Soon',
    // AI Analyst
    backToCase: 'Back to Case',
    aiAnalyst_instructions_activeCase: 'Add a new AI analysis artifact to the current case.',
    aiAnalyst_instructions_newCase: 'Start a new investigation. The AI will perform an initial analysis which will be saved to a new case.',
    pasteText: 'Paste Text',
    uploadFiles: 'Upload Files',
    eventLogDescription: 'Event Log / Description',
    pasteLogPlaceholder: 'Paste your security log, alert details, or incident description here...',
    eventFiles: 'Event Files (e.g., JSON, XML, TXT, LOG)',
    uploadOrDrag: 'Upload files or drag and drop',
    orDragAndDrop: 'or drag and drop',
    useExampleLog: 'Use Example Log',
    analyzeEvent: 'Analyze Event',
    analyzing: 'Analyzing...',
    analysisError: 'Analysis Error',
    error_enterLogOrFile: 'Please paste an event log or upload files before analyzing.',
    error_analysisFailed: 'Failed to analyze the event. The AI model might be unavailable or the input is invalid. Please try again.',
    aiAnalyzingEvent: 'AI is analyzing the event...',
    resultWillBeAdded: 'The result will be automatically added to your case.',
    analysisComplete: 'Analysis Complete!',
    analysisSavedToCase: 'This analysis has been saved as an artifact in your case. You can now return to the case view.',
    // Casebook & Create Case Modal
    createNewCase: 'Create New Case',
    caseName: 'Case Name',
    caseName_placeholder: 'e.g., Phishing Incident - J.Doe - 2024-08-15',
    description: 'Description',
    description_placeholder: 'Briefly describe the incident or investigation.',
    createCase: 'Create Case',
    investigationCasebook: 'Investigation Casebook',
    openCases: 'Open Cases',
    noCasesFound: 'No cases found',
    createFirstCase: 'Create your first case to begin an investigation.',
    noDescription: 'No description',
    created: 'Created',
    basicInfo: 'Basic Info (Required)',
    initialFindings: 'Initial Findings (Optional)',
    incidentSummary: 'Incident Summary',
    incidentSummary_placeholder: 'Paste the initial alert, ticket summary, or a brief overview of the incident.',
    preliminaryNotes: 'Preliminary Notes',
    preliminaryNotes_placeholder: 'Add any initial thoughts, findings, or questions you have.',
    toolingContext: 'Tooling Context (Optional)',
    // Case Detail View
    backToCasebook: 'Back to Casebook',
    caseIntelligenceBriefing: 'Case Intelligence Briefing',
    globalSummaryGenerating: 'Global summary is being generated...',
    globalIoCGenerating: 'Global IoC list is being generated...',
    investigationPlan: 'Investigation Plan',
    thinking: 'Thinking...',
    suggestNextSteps: 'Suggest Next Steps',
    investigationContext: 'Investigation Context',
    addToolInfo: 'Add Tool Info',
    noToolsLogged: 'No tools logged yet. Add tools used to improve AI suggestions.',
    analystInbox: 'Analyst Inbox',
    addToInbox: 'Add to Inbox',
    inboxIsClear: 'Inbox is clear. Add new findings here for the AI to organize.',
    runNewAIAnalysis: 'Run New AI Analysis on Evidence',
    addArtifact: 'Add Artifact',
    noArtifactsForPhase: 'No artifacts for this phase yet.',
    phaseContainsArtifacts: 'Phase contains {count} artifact(s)',
    caseAssistant: 'Case Assistant',
    // Artifact Card
    tool: 'Tool',
    command: 'Command',
    output: 'Output',
    fileName: 'File Name',
    content: 'Content',
    version: 'Version',
    config: 'Config',
    noIocsIdentified: 'No Indicators of Compromise have been identified yet.',
    unsupportedArtifact: 'Unsupported or malformed artifact content.',
    organizeWithAI: 'Organize with AI',
    // Add Artifact Modal
    toPhase: 'To phase',
    analystNote: 'Analyst Note',
    toolOutput: 'Tool Output',
    evidenceFile: 'Evidence File',
    toolInfo: 'Tool Info',
    noteTitle_placeholder: 'Note title*',
    noteText_placeholder: 'Your notes here...*',
    toolName_placeholder: 'Tool Name (e.g., Splunk, Nmap)*',
    toolCommand_placeholder: 'Command Run (Optional)',
    toolOutput_placeholder: 'Paste tool output here...*',
    evidenceTitle_placeholder: 'Title for this evidence*',
    clickToUpload: 'Click to upload',
    textBasedFiles: 'Text-based files (.log, .txt, .json, etc.)',
    toolInfo_desc: 'Log a tool used in this investigation to give the AI agents better context.',
    toolInfoName_placeholder: 'Tool Name (e.g., Splunk, Wireshark)',
    toolInfoVersion_placeholder: 'Version (e.g., 9.1.0)',
    toolInfoConfig_placeholder: 'Configuration or relevant details (e.g., Splunk add-ons)',
    cancel: 'Cancel',
    addToCase: 'Add to Case',
    // Investigation Checklist
    noInvestigationSteps: 'No investigation steps have been generated yet. Click "Suggest Next Steps" to get started.',
    overallProgress: 'Overall Progress',
    stepsCompleted: '{completed} / {total} Steps Completed',
    // Split Artifact Modal
    aiOrganizationPlan: 'AI Organization Plan',
    aiOrganizationPlan_desc: 'The AI has analyzed your note and proposes splitting it into the following new artifacts. Review the plan below.',
    analyzingAndSplitting: 'Analyzing and splitting artifact...',
    error_splitSuggestionFailed: 'Failed to get a split suggestion from the AI. The note may be too short or the content unclear.',
    approveAndOrganize: 'Approve & Organize',
    // Chat
    chat_placeholder: 'Ask the assistant about this case...',
    send: 'Send',
    assistant_greeting: 'I am the Cyber Sentinel Case Assistant. How can I help you analyze this investigation?',
    // Kill Chain Phases
    Reconnaissance: 'Reconnaissance',
    Weaponization: 'Weaponization',
    Delivery: 'Delivery',
    Exploitation: 'Exploitation',
    Installation: 'Installation',
    'Command and Control': 'Command and Control',
    'Actions on Objectives': 'Actions on Objectives',
    Uncategorized: 'Uncategorized',
    // VT Scanner & Details
    noteOnSpeed: 'Note on Speed: The free VirusTotal Public API has a strict rate limit. Select a speed that matches your API key type. Scans of large lists will take time.',
    noteOnConnectivity: 'Note on Connectivity: To bypass browser security policies (CORS), this tool routes requests through a free, public proxy (corsproxy.io). If you see a network error, the proxy or VirusTotal\'s API may be temporarily unavailable.',
    scannerConfig: 'Scanner Configuration',
    vtApiKey: 'VirusTotal API Key',
    vtApiKey_placeholder: 'Leave blank to use the default key',
    hideApiKey: 'Hide API key',
    showApiKey: 'Show API key',
    keyNotStored: 'Your key is not stored.',
    scanSpeed: 'Scan Speed',
    speedSlow_label: 'Slow (Free Key)',
    speedSlow_desc: '4 items / min',
    speedMedium_label: 'Medium (Premium Key)',
    speedMedium_desc: '60 items / min',
    speedFast_label: 'Fast (Premium Key)',
    speedFast_desc: '240 items / min',
    scan: 'Scan',
    scanning: 'Scanning...',
    domains: 'Domains',
    fileHashes: 'File Hashes',
    ipAddresses: 'IP Addresses',
    urls: 'URLs',
    pasteList: 'Paste List',
    uploadFile: 'Upload File',
    domains_placeholder: 'Paste domains here, one per line or separated by spaces/commas...',
    hashes_placeholder: 'Paste file hashes (MD5, SHA1, SHA256) here...',
    ips_placeholder: 'Paste IP addresses here...',
    urls_placeholder: 'Paste full URLs (e.g., http://example.com/page) here...',
    upload_desc: '.TXT or .CSV file',
    scanResults: 'Scan Results',
    saveAsCsv: 'Save as CSV',
    ready: 'Ready',
    noResults: 'No results to display. Start a new scan.',
    loading: 'Loading',
    vt_fileAnalysis: 'File Analysis',
    vt_ipAnalysis: 'IP Address Analysis',
    vt_urlAnalysis: 'URL Analysis',
    vt_domainAnalysis: 'Domain Analysis',
    vt_relationships: 'Relationships',
    vt_summary: 'Summary',
    vt_fileProperties: 'File Properties',
    vt_mainName: 'Main Name',
    vt_size: 'Size',
    vt_type: 'Type',
    vt_magic: 'Magic String',
    vt_signature: 'Signature',
    vt_otherNames: 'Other Known Names',
    vt_noOtherNames: 'No other names recorded.',
    vt_contactedDomains: 'Contacted Domains',
    vt_noContactedDomains: 'No contacted domains found.',
    vt_contactedIps: 'Contacted IPs',
    vt_noContactedIps: 'No contacted IPs found.',
    vt_domain: 'Domain',
    vt_ipAddress: 'IP Address',
    vt_detections: 'Detections',
    vt_reputation: 'Reputation',
    vt_ipProperties: 'IP Properties',
    vt_owner: 'Owner',
    vt_asn: 'ASN',
    vt_country: 'Country',
    vt_rir: 'RIR',
    vt_network: 'Network',
    vt_domainResolutions: 'Domain Resolutions',
    vt_hostname: 'Hostname',
    vt_lastSeen: 'Last Seen',
    vt_noResolutions: 'No domain resolutions found.',
    vt_associatedFiles: 'Associated Files',
    vt_noAssociatedFiles: 'No associated files found.',
    vt_urlProperties: 'URL Properties',
    vt_pageTitle: 'Page Title',
    vt_finalUrl: 'Final URL',
    vt_responseCode: 'Response Code',
    vt_categories: 'Categories',
    vt_noCategories: 'No categories assigned.',
    vt_downloadedFiles: 'Downloaded Files',
    vt_noDownloadedFiles: 'No downloaded files found.',
    // User Agent Analyzer
    uaAnalyzer_desc: 'Analyze User-Agent strings for technical details and potential security risks using AI.',
    pasteUA_placeholder: 'Paste one or more User-Agent strings here, one per line...',
    analyze: 'Analyze',
    parsedInformation: 'Parsed Information',
    aiSecurityAnalysis: 'AI Security Analysis',
    riskLevel: 'Risk Level',
    error_uaParse: 'Failed to parse User-Agent. The external service may be down or the User-Agent is malformed.',
    error_uaSecurity: 'Failed to get security analysis from the AI model.',
    browser: 'Browser',
    os: 'Operating System',
    platform: 'Platform',
    engine: 'Engine',
    securityFlags: 'Security Flags',
    bot: 'Bot',
    crawler: 'Crawler',
    evil: 'Potentially Malicious',
    proxy: 'Proxy',
    vpn: 'VPN',
    tor: 'Tor',
    known_attacker: 'Known Attacker',
    known_scanner: 'Known Scanner',
    known_spammer: 'Known Spammer',
    known_bot: 'Known Bot',
    known_search_engine: 'Search Engine',
    known_social_media: 'Social Media',
    known_adware: 'Known Adware',
    known_malware: 'Known Malware',
    known_phishing: 'Known Phishing',
    known_exploit: 'Known Exploit',
    known_ddos: 'Known DDoS',
    known_trojan: 'Known Trojan',
    known_worm: 'Known Worm',
    known_ransomware: 'Known Ransomware',
    known_spyware: 'Known Spyware',
    known_keylogger: 'Known Keylogger',
  },
  ar: {
    cyberSentinel: 'الحارس السيبراني',
    // Main Menu
    casebook: 'سجل القضايا',
    newInvestigation: 'تحقيق جديد',
    vtScanner: 'فاحص VirusTotal',
    uaAnalyzer: 'محلل وكيل المستخدم',
    vulnScanner: 'فاحص الثغرات',
    threatIntel: 'تغذية معلومات التهديدات',
    soon: 'قريباً',
    // AI Analyst
    backToCase: 'العودة إلى القضية',
    aiAnalyst_instructions_activeCase: 'أضف قطعة أثرية جديدة للتحليل بالذكاء الاصطناعي إلى القضية الحالية.',
    aiAnalyst_instructions_newCase: 'ابدأ تحقيقًا جديدًا. سيقوم الذكاء الاصطناعي بإجراء تحليل أولي سيتم حفظه في قضية جديدة.',
    pasteText: 'لصق نص',
    uploadFiles: 'رفع ملفات',
    eventLogDescription: 'سجل الحدث / الوصف',
    pasteLogPlaceholder: 'الصق سجل الأمان أو تفاصيل التنبيه أو وصف الحادث هنا...',
    eventFiles: 'ملفات الحدث (مثل JSON، XML، TXT، LOG)',
    uploadOrDrag: 'ارفع الملفات أو اسحبها وأفلتها',
    orDragAndDrop: 'أو السحب والإفلات',
    useExampleLog: 'استخدم سجل كمثال',
    analyzeEvent: 'تحليل الحدث',
    analyzing: 'جاري التحليل...',
    analysisError: 'خطأ في التحليل',
    error_enterLogOrFile: 'يرجى لصق سجل حدث أو رفع ملفات قبل التحليل.',
    error_analysisFailed: 'فشل تحليل الحدث. قد يكون نموذج الذكاء الاصطناعي غير متاح أو الإدخال غير صالح. يرجى المحاولة مرة أخرى.',
    aiAnalyzingEvent: 'يقوم الذكاء الاصطناعي بتحليل الحدث...',
    resultWillBeAdded: 'ستتم إضافة النتيجة تلقائيًا إلى قضيتك.',
    analysisComplete: 'اكتمل التحليل!',
    analysisSavedToCase: 'تم حفظ هذا التحليل كقطعة أثرية في قضيتك. يمكنك الآن العودة إلى عرض القضية.',
    // Casebook & Create Case Modal
    createNewCase: 'إنشاء قضية جديدة',
    caseName: 'اسم القضية',
    caseName_placeholder: 'مثال: حادثة تصيد - J.Doe - 2024-08-15',
    description: 'الوصف',
    description_placeholder: 'صف الحادث أو التحقيق بإيجاز.',
    createCase: 'إنشاء قضية',
    investigationCasebook: 'سجل قضايا التحقيق',
    openCases: 'القضايا المفتوحة',
    noCasesFound: 'لم يتم العثور على قضايا',
    createFirstCase: 'أنشئ قضيتك الأولى لبدء التحقيق.',
    noDescription: 'لا يوجد وصف',
    created: 'تم الإنشاء',
    basicInfo: 'المعلومات الأساسية (مطلوبة)',
    initialFindings: 'النتائج الأولية (اختياري)',
    incidentSummary: 'ملخص الحادث',
    incidentSummary_placeholder: 'الصق التنبيه الأولي، ملخص التذكرة، أو نظرة عامة موجزة عن الحادث.',
    preliminaryNotes: 'الملاحظات الأولية',
    preliminaryNotes_placeholder: 'أضف أي أفكار أو نتائج أو أسئلة أولية لديك.',
    toolingContext: 'سياق الأدوات (اختياري)',
    // Case Detail View
    backToCasebook: 'العودة إلى سجل القضايا',
    caseIntelligenceBriefing: 'ملخص استخبارات القضية',
    globalSummaryGenerating: 'جاري إنشاء الملخص العام...',
    globalIoCGenerating: 'جاري إنشاء قائمة المؤشرات العامة...',
    investigationPlan: 'خطة التحقيق',
    thinking: 'جاري التفكير...',
    suggestNextSteps: 'اقتراح الخطوات التالية',
    investigationContext: 'سياق التحقيق',
    addToolInfo: 'إضافة معلومات الأداة',
    noToolsLogged: 'لم يتم تسجيل أي أدوات بعد. أضف الأدوات المستخدمة لتحسين اقتراحات الذكاء الاصطناعي.',
    analystInbox: 'صندوق الوارد للمحلل',
    addToInbox: 'إضافة إلى صندوق الوارد',
    inboxIsClear: 'صندوق الوارد فارغ. أضف النتائج الجديدة هنا ليقوم الذكاء الاصطناعي بتنظيمها.',
    runNewAIAnalysis: 'إجراء تحليل جديد بالذكاء الاصطناعي على الأدلة',
    addArtifact: 'إضافة قطعة أثرية',
    noArtifactsForPhase: 'لا توجد قطع أثرية لهذه المرحلة حتى الآن.',
    phaseContainsArtifacts: 'المرحلة تحتوي على {count} قطعة أثرية',
    caseAssistant: 'مساعد القضية',
    // Artifact Card
    tool: 'الأداة',
    command: 'الأمر',
    output: 'الناتج',
    fileName: 'اسم الملف',
    content: 'المحتوى',
    version: 'الإصدار',
    config: 'الإعدادات',
    noIocsIdentified: 'لم يتم تحديد أي مؤشرات اختراق حتى الآن.',
    unsupportedArtifact: 'محتوى قطعة أثرية غير مدعوم أو تالف.',
    organizeWithAI: 'تنظيم بواسطة الذكاء الاصطناعي',
    // Add Artifact Modal
    toPhase: 'إلى مرحلة',
    analystNote: 'ملاحظة محلل',
    toolOutput: 'ناتج أداة',
    evidenceFile: 'ملف دليل',
    toolInfo: 'معلومات أداة',
    noteTitle_placeholder: 'عنوان الملاحظة*',
    noteText_placeholder: 'ملاحظاتك هنا...*',
    toolName_placeholder: 'اسم الأداة (مثل Splunk, Nmap)*',
    toolCommand_placeholder: 'الأمر الذي تم تشغيله (اختياري)',
    toolOutput_placeholder: 'الصق ناتج الأداة هنا...*',
    evidenceTitle_placeholder: 'عنوان هذا الدليل*',
    clickToUpload: 'انقر للرفع',
    textBasedFiles: 'ملفات نصية (.log, .txt, .json, etc.)',
    toolInfo_desc: 'سجل أداة مستخدمة في هذا التحقيق لإعطاء وكلاء الذكاء الاصطناعي سياقًا أفضل.',
    toolInfoName_placeholder: 'اسم الأداة (مثل Splunk, Wireshark)',
    toolInfoVersion_placeholder: 'الإصدار (مثل 9.1.0)',
    toolInfoConfig_placeholder: 'الإعدادات أو التفاصيل ذات الصلة (مثل إضافات Splunk)',
    cancel: 'إلغاء',
    addToCase: 'إضافة إلى القضية',
    // Investigation Checklist
    noInvestigationSteps: 'لم يتم إنشاء خطوات تحقيق بعد. انقر على "اقتراح الخطوات التالية" للبدء.',
    overallProgress: 'التقدم العام',
    stepsCompleted: 'اكتمل {completed} / {total} من الخطوات',
    // Split Artifact Modal
    aiOrganizationPlan: 'خطة التنظيم بالذكاء الاصطناعي',
    aiOrganizationPlan_desc: 'حلل الذكاء الاصطناعي ملاحظتك ويقترح تقسيمها إلى القطع الأثرية الجديدة التالية. راجع الخطة أدناه.',
    analyzingAndSplitting: 'جاري تحليل وتقسيم القطعة الأثرية...',
    error_splitSuggestionFailed: 'فشل الحصول على اقتراح تقسيم من الذكاء الاصطناعي. قد تكون الملاحظة قصيرة جدًا أو المحتوى غير واضح.',
    approveAndOrganize: 'الموافقة والتنظيم',
    // Chat
    chat_placeholder: 'اسأل المساعد عن هذه القضية...',
    send: 'إرسال',
    assistant_greeting: 'أنا مساعد قضية الحارس السيبراني. كيف يمكنني مساعدتك في تحليل هذا التحقيق؟',
    // Kill Chain Phases
    Reconnaissance: 'استطلاع',
    Weaponization: 'تسليح',
    Delivery: 'توصيل',
    Exploitation: 'استغلال',
    Installation: 'تثبيت',
    'Command and Control': 'القيادة والتحكم',
    'Actions on Objectives': 'الإجراءات على الأهداف',
    Uncategorized: 'غير مصنف',
    // VT Scanner & Details
    noteOnSpeed: 'ملاحظة حول السرعة: واجهة برمجة تطبيقات VirusTotal العامة المجانية لها حد صارم للمعدل. حدد سرعة تتوافق مع نوع مفتاح API الخاص بك. ستستغرق عمليات فحص القوائم الكبيرة وقتًا.',
    noteOnConnectivity: 'ملاحظة حول الاتصال: لتجاوز سياسات أمان المتصفح (CORS)، تقوم هذه الأداة بتوجيه الطلبات عبر وكيل عام مجاني (corsproxy.io). إذا رأيت خطأ في الشبكة، فقد يكون الوكيل أو واجهة برمجة تطبيقات VirusTotal غير متاحين مؤقتًا.',
    scannerConfig: 'إعدادات الفاحص',
    vtApiKey: 'مفتاح API الخاص بـ VirusTotal',
    vtApiKey_placeholder: 'اتركه فارغًا لاستخدام المفتاح الافتراضي',
    hideApiKey: 'إخفاء مفتاح API',
    showApiKey: 'إظهار مفتاح API',
    keyNotStored: 'لا يتم تخزين مفتاحك.',
    scanSpeed: 'سرعة الفحص',
    speedSlow_label: 'بطيء (مفتاح مجاني)',
    speedSlow_desc: '4 عناصر / دقيقة',
    speedMedium_label: 'متوسط (مفتاح مدفوع)',
    speedMedium_desc: '60 عنصرًا / دقيقة',
    speedFast_label: 'سريع (مفتاح مدفوع)',
    speedFast_desc: '240 عنصرًا / دقيقة',
    scan: 'فحص',
    scanning: 'جاري الفحص...',
    domains: 'النطاقات',
    fileHashes: 'تجزئات الملفات',
    ipAddresses: 'عناوين IP',
    urls: 'عناوين URL',
    pasteList: 'لصق قائمة',
    uploadFile: 'رفع ملف',
    domains_placeholder: 'الصق النطاقات هنا، واحد في كل سطر أو مفصولة بمسافات/فواصل...',
    hashes_placeholder: 'الصق تجزئات الملفات (MD5, SHA1, SHA256) هنا...',
    ips_placeholder: 'الصق عناوين IP هنا...',
    urls_placeholder: 'الصق عناوين URL الكاملة (مثل http://example.com/page) هنا...',
    upload_desc: 'ملف .TXT أو .CSV',
    scanResults: 'نتائج الفحص',
    saveAsCsv: 'حفظ كـ CSV',
    ready: 'جاهز',
    noResults: 'لا توجد نتائج لعرضها. ابدأ فحصًا جديدًا.',
    loading: 'جار التحميل',
    vt_fileAnalysis: 'تحليل الملف',
    vt_ipAnalysis: 'تحليل عنوان IP',
    vt_urlAnalysis: 'تحليل الرابط',
    vt_domainAnalysis: 'تحليل النطاق',
    vt_relationships: 'العلاقات',
    vt_summary: 'ملخص',
    vt_fileProperties: 'خصائص الملف',
    vt_mainName: 'الاسم الرئيسي',
    vt_size: 'الحجم',
    vt_type: 'النوع',
    vt_magic: 'سلسلة Magic',
    vt_signature: 'التوقيع',
    vt_otherNames: 'أسماء أخرى معروفة',
    vt_noOtherNames: 'لا توجد أسماء أخرى مسجلة.',
    vt_contactedDomains: 'النطاقات المتصل بها',
    vt_noContactedDomains: 'لم يتم العثور على نطاقات متصل بها.',
    vt_contactedIps: 'عناوين IP المتصل بها',
    vt_noContactedIps: 'لم يتم العثور على عناوين IP متصل بها.',
    vt_domain: 'النطاق',
    vt_ipAddress: 'عنوان IP',
    vt_detections: 'الاكتشافات',
    vt_reputation: 'السمعة',
    vt_ipProperties: 'خصائص IP',
    vt_owner: 'المالك',
    vt_asn: 'ASN',
    vt_country: 'الدولة',
    vt_rir: 'RIR',
    vt_network: 'الشبكة',
    vt_domainResolutions: 'تحليلات النطاق',
    vt_hostname: 'اسم المضيف',
    vt_lastSeen: 'آخر مشاهدة',
    vt_noResolutions: 'لم يتم العثور على تحليلات نطاق.',
    vt_associatedFiles: 'الملفات المرتبطة',
    vt_noAssociatedFiles: 'لم يتم العثور على ملفات مرتبطة.',
    vt_urlProperties: 'خصائص الرابط',
    vt_pageTitle: 'عنوان الصفحة',
    vt_finalUrl: 'الرابط النهائي',
    vt_responseCode: 'رمز الاستجابة',
    vt_categories: 'الفئات',
    vt_noCategories: 'لا توجد فئات معينة.',
    vt_downloadedFiles: 'الملفات التي تم تنزيلها',
    vt_noDownloadedFiles: 'لم يتم العثور على ملفات تم تنزيلها.',
    // User Agent Analyzer
    uaAnalyzer_desc: 'حلل سلاسل وكيل المستخدم للحصول على تفاصيل تقنية ومخاطر أمنية محتملة باستخدام الذكاء الاصطناعي.',
    pasteUA_placeholder: 'الصق سلسلة أو أكثر من وكلاء المستخدم هنا، واحد في كل سطر...',
    analyze: 'تحليل',
    parsedInformation: 'المعلومات المفصلة',
    aiSecurityAnalysis: 'التحليل الأمني بالذكاء الاصطناعي',
    riskLevel: 'مستوى الخطورة',
    error_uaParse: 'فشل في تحليل وكيل المستخدم. قد تكون الخدمة الخارجية معطلة أو أن وكيل المستخدم غير صالح.',
    error_uaSecurity: 'فشل في الحصول على التحليل الأمني من نموذج الذكاء الاصطناعي.',
    browser: 'المتصفح',
    os: 'نظام التشغيل',
    platform: 'المنصة',
    engine: 'المحرك',
    securityFlags: 'علامات الأمان',
    bot: 'بوت',
    crawler: 'زاحف',
    evil: 'يحتمل أن يكون ضارًا',
    proxy: 'وكيل',
    vpn: 'VPN',
    tor: 'Tor',
    known_attacker: 'مهاجم معروف',
    known_scanner: 'فاحص معروف',
    known_spammer: 'مرسل بريد مزعج معروف',
    known_bot: 'بوت معروف',
    known_search_engine: 'محرك بحث',
    known_social_media: 'وسائط اجتماعية',
    known_adware: 'برامج إعلانية معروفة',
    known_malware: 'برامج ضارة معروفة',
    known_phishing: 'تصيد معروف',
    known_exploit: 'استغلال معروف',
    known_ddos: 'هجوم حجب خدمة معروف',
    known_trojan: 'طروادة معروف',
    known_worm: 'دودة معروفة',
    known_ransomware: 'برامج فدية معروفة',
    known_spyware: 'برامج تجسس معروفة',
    known_keylogger: 'مسجل نقرات مفاتيح معروف',
  },
};


const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>(() => {
    const savedLocale = localStorage.getItem('cyberSentinelLocale');
    return (savedLocale === 'ar' || savedLocale === 'en') ? savedLocale : 'en';
  });

  const direction = useMemo(() => (locale === 'ar' ? 'rtl' : 'ltr'), [locale]);

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = direction;
  }, [locale, direction]);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('cyberSentinelLocale', newLocale);
  };
  
  const t = (key: string, options?: Record<string, string | number>): string => {
    let translation = translations[locale][key] || translations['en'][key] || key;
    if (options) {
      Object.keys(options).forEach(optionKey => {
        translation = translation.replace(`{${optionKey}}`, String(options[optionKey]));
      });
    }
    return translation;
  };


  return (
    <LocalizationContext.Provider value={{ locale, direction, t, setLocale }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = (): LocalizationContextType => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};